# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

pr_cpp <- function(f0, U, X, d, N, w) {
    .Call(`_PredictiveRecursion_pr_cpp`, f0, U, X, d, N, w)
}

